name: Build gRPC User Operations Service

on:
  push:
    branches:
      - '*'

jobs:

  Build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1

      - name: Install requirements
        run: |
          pip install -r requirements.txt    
          pip install -r requirements-test.txt
          pip install -e src/  
      
      - name: Generate Protobufs files
        run: |
            make generate-protos  

      - name: Make Unit Test
        run: |
            make unit-test  
      
      - name: Make Integration Test
        run: |
            make integration-test
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432